name: "onReleasePullRequestUpdated"

on:
  pull_request:
    types:
      - edited
    branches:
      - master
env:
  CI: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    if: startsWith(github.head_ref, 'release/next')
    env:
      CHANGELOG_FILE: ./CHANGELOG.md
      CHANGELOG_OLD_FILE: ./CHANGELOG.old.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Identity
        run: |
          git config --global user.name 'alexm122322'
          git config --global user.email 'alexm122322@gmail.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Incremented version
        uses: actions/github-script@v6
        id: incremented-version
        with:
          result-encoding: string
          script: |
            const {default: fs} = await import('fs');
            let content = fs.readFileSync('./pubspec.yaml', {encoding: "utf-8"});
            const currentVersion = /version:[ ]+([^\n]+)/g.exec(content)[1];
            const version = currentVersion.split('.');
            const newVersion = `${version[0]}.${version[1]}.${parseInt(version[2]) + 1}`;
            
            content = content.replace(/version:[ ]+([^\n]+)/g, `version: ${newVersion}`);
            fs.writeFileSync('./pubspec.yaml', content);
            fs.writeFileSync('version.txt', newVersion);
            return newVersion;

      - name: Pull Request Description
        id: get_description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # Append current PR description if available
          if [[ -n "${{ github.event.pull_request.number }}" ]]; then
            PR_METADATA=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          
            CURRENT_PR_BODY=$(echo "$PR_METADATA" | jq -r '.body // ""')
            DESCRIPTION="$DESCRIPTION"$'\n'"$CURRENT_PR_BODY"
          fi
          
          # Store in GitHub Actions output
          {
            echo 'DESCRIPTION<<EOF'
            echo "$DESCRIPTION"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Update CHANGELOG file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |  
          # Append PR description to CHANGELOG_FILE safely
          if [[ -f "${{ env.CHANGELOG_FILE }}" ]]; then
            echo -e "${{ steps.get_description.outputs.DESCRIPTION }}\n\n$(cat ${{ env.CHANGELOG_FILE }})" > ${{ env.CHANGELOG_FILE }}
          else
            echo "${{ steps.get_description.outputs.DESCRIPTION }}" > ${{ env.CHANGELOG_FILE }}
          fi

      - name: Commit changes
        shell: bash -ex {0}
        run: |
          git add . && git commit -m "chore(release): publish ${{ steps.incremented-version.outputs.result }}"

      - name: Create Release Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ secrets.GITHUB_WORKSPACE }}
          commit-message: "Update v${{ steps.incremented-version.outputs.result }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: 'v${{ steps.incremented-version.outputs.result }}'
          body: '${{ steps.get_description.outputs.DESCRIPTION }}'
          base: "master"
          labels: "Type: Release"
          branch: "release/next"
