name: "onReleasePullRequestUpdated"

on:
  pull_request:
    types:
      - edited
    branches:
      - master

jobs:
  build:
    runs-on: 'ubuntu-latest'
    if: startsWith(github.head_ref, 'release/next')
    env:
      CHANGELOG_FILE: ./CHANGELOG.md
      CHANGELOG_OLD_FILE: ./CHANGELOG.old.md
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: release/next

      - name: Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          pr_metadata=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github+json" \
           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")
          
          # Extract the description (body field)
          DESCRIPTION=$(echo "$pr_metadata" | jq -r '.body // ""')
          
          # Check if DESCRIPTION is valid
          if [[ -n "$DESCRIPTION" && "$DESCRIPTION" != "null" ]]; then
            if [[ -f "${{ env.CHANGELOG_OLD_FILE }}" ]]; then
              printf "%s\n\n%s\n" "${{ steps.get_description.outputs.DESCRIPTION }}" "$(cat ${{ env.CHANGELOG_OLD_FILE }})" > ${{ env.CHANGELOG_FILE }}
            else
              echo "${{ steps.get_description.outputs.DESCRIPTION }}" > ${{ env.CHANGELOG_FILE }}
            fi
          else
            echo "No description provided in the pull request. The 'release/next' branch must provide a description for correct CHANGELOG.md generation."
            exit 1
          fi

      - name: Commit changes
        shell: bash
        run: |
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m "chore(release): UPDATED CHANGELOG.md"
          git push origin "${{ github.ref_name }}"
