name: Publish release to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  publish:
    permissions:
      contents: write
      actions: write
      id-token: write # Required for authentication using OIDC
    #    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    name: 'Publish to pub.dev'
    runs-on: 'macos-latest-large'
    steps:
      - name: Print
        run: echo "DONE"
